site_name: "Nuitka The Python Compiler"
site_url: https://nuitka.net/
site_description: Python Compiler
site_author: Kay Hayen

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/images/nuitka-logo.svg
  favicon: assets/images/nuitka-logo.svg
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy

extra_css:
  - stylesheets/pinwheel.css

extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/kayhayen
      name: Nuitka on Twitter
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/nuitka
      name: Nuitka on Facebook
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@nuitka
      name: Nuitka on Mastodon
    - icon: fontawesome/brands/reddit
      link: https://reddit.com/r/nuitka
      name: Nuitka on Reddit
    - icon: fontawesome/brands/github
      link: https://github.com/Nuitka/Nuitka
      name: Nuitka on GitHub

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - optimize:
      enabled: true
      optimize_png: true
      optimize_jpg: true
      optimize_svg: true
      print_gain: true
      print_gain_summary: true

nav:
  - Home: index.md
  - Download: download.md
  - User Documentation:
    - Overview: user-documentation.md
    - User Manual: user-manual.md
    - 'Tutorial: Setup and Build': tutorial-setup-and-build.md
    - Tips: tips.md
    - Performance: performance.md
    - Use Cases: use-cases.md
    - Package Configuration: package-configuration.md
    - Common Issue Solutions: common-issue-solutions.md
  - Support: support.md
  - Contribute: 
    - Overview: contribute.md
    - Donations: donations.md
    - Website Manual: website-manual.md
    - Developer Manual: developer-manual.md
    - API Documentation: api-doc.md
  - Commercial Users:
    - Overview: commercial.md
    - Purchase: commercial/purchase.md
    - Reseller Information: commercial/resellers.md
    - Nuitka VM: commercial/nuitka-vm.md
  - News and Blog:
    - Blog: blog.md
    - Release Information:
      - Overview: changelog.md
      - Current Release: changelog/current.md
      - Roadmap: changelog/roadmap.md
      - Next Release: changelog/next.md
      - Version 2.x: changelog/changelog-2x.md
      - Version 1.x: changelog/changelog-1x.md
      - Version 0.x: changelog/changelog-0x.md
    - Streaming: streaming.md
    - News:
      - All In With Nuitka: news/all-in-with-nuitka.md
      - Nuitka Release 2.7: news/nuitka-release-27.md
  - Other:
    - Credits: credits.md
    - Impressum: impressum.md
    - PySide2 Support: other/pyside2-support.md
    - PyQt5 Support: other/pyqt5-support.md
